### ISSUE TITLE
Sturm der Liebe neue Folgen nicht abspielbar

### ISSUE THREAD

**Issue by snodo** [prof-membrane/plugin.video.ardmediathek_de#29]
Betriebssystem: LibreELEC 8.2.5 (RPi2.arm) und Windows 10 (64 Bit mit 32 Bit Kodi)
Kodi Version: 17.6 (auf beiden Systemen die gleiche GIT: a9a7a20)
Add-on Version: 5.1.0 (jeweils über das repository.membrane.zip Addon-Repository installiert)
Bibliothek: libard

Nachdem es auf dem Raspi nicht lief, hab ichs unter Windows gegen gecheckt -> gleiches Ergebnis.
In der ARD Mediathek -> Sendungen A-Z -> Sturm der Liebe (das obere der beiden) -> Folge 3004 geht noch, ab Folge 3005 nicht mehr.

Hier die Log, wenn man versucht Folge 3005 abzuspielen:

```
11:58:41.771 T:10260   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'finalUrl' referenced before assignment
                                            Traceback (most recent call last):
                                              File "C:\Users\snodo\AppData\Roaming\Kodi\addons\plugin.video.ardmediathek_de\default.py", line 4, in <module>
                                                libard.list()
                                              File "C:\Users\snodo\AppData\Roaming\Kodi\addons\script.module.libard\lib\libard.py", line 142, in list
                                                libMediathek.play(libArdPlay())
                                              File "C:\Users\snodo\AppData\Roaming\Kodi\addons\script.module.libard\lib\libard.py", line 135, in libArdPlay
                                                return libardplayer.getVideoUrl(videoID = params['documentId'])
                                              File "C:\Users\snodo\AppData\Roaming\Kodi\addons\script.module.libard\lib\libardplayer.py", line 24, in getVideoUrl
                                                return fetchJsonVideo(videoID)
                                              File "C:\Users\snodo\AppData\Roaming\Kodi\addons\script.module.libard\lib\libardplayer.py", line 37, in fetchJsonVideo
                                                if finalUrl.startswith('//'):
                                            UnboundLocalError: local variable 'finalUrl' referenced before assignment
                                            -->End of Python script error report<--
11:58:41.781 T:12460   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.ardmediathek_de/?documentId=56424542&url=https%3A%2F%2Fappdata.ardmediathek.de%2Fappdata%2Fservlet%2Ftv%2Fplayer%2F56424542%3FbcastId%3D5290%26json&mode=libArdPlay]
```

Ist zum Glück nicht ganz so dramatisch, denn in der "Das Erste"-Mediathek klappen die Folgen.

Desweiteren gibt es auch bei KiKa Probleme mit "Die Sendung mit dem Elefanten" - dafür gibts aber keinen Issue-Tracker. Wo kann ich das loswerden?

**Comment by 68000a** [comment]
Zum ersten Problem (ARD):
schau mal [hier](https://www.kodinerds.net/index.php/Thread/4055-Mein-Repo-f%C3%BCr-verschiedene-Videoaddons/?postID=489593#post489593)

Zum zweiten Problem (KiKa):
schau mal [hier](https://www.kodinerds.net/index.php/Thread/4055-Mein-Repo-f%C3%BCr-verschiedene-Videoaddons/?postID=492102#post492102)

Und noch 'ne Frage: Wo finde ich denn die "Das Erste"-Mediathek ???
Ich hab' im Repo nur die ARD und die ganzen Dritten als getrennte Mediatheken.

**Comment by snodo** [comment]
Genial, die beiden Patches werde ich mal ausprobieren. Mal sehen, ob ich das unter der Woche schaffe, oder erst am Wochenende.

Bin selbst Python-Entwickler und hatte auch mal kurz rein geschaut, aber als es mit nem simplen Umschalten der Qualität bei mir irgendwie nicht getan war, hab ich gar keine weitere Arbeit reingesteckt - wahrscheinlich hab ich auch irgendwelche Pfade beim Basteln schief umgebogen, als ich in den Dicts rumgefuchtelt hab ;)

Zur "Das Erste"-Mediathek:
Ich hab einfach wie in der README.md beschrieben das repository.membrane.zip runtergeladen, installiert und bei mir zeigt Kodi dann ein entsprechendes Video-Plugin an. (Wie gesagt: Durchgeführt hab ich das ganze auf nem Raspi und auch Windows)

**Comment by 68000a** [comment]
Vielen Dank! Hab' einfach vergessen "Das Erste" aus dem Repo zu installieren, deshalb tauchte es nicht im AddOn-Menü auf.

**Comment by 68000a** [comment]
Es gibt ein Update, schaut mal [hier](https://www.kodinerds.net/index.php/Thread/4055-Mein-Repo-f%C3%BCr-verschiedene-Videoaddons/?postID=496740#post496740)
