### ISSUE TITLE
ARD Mediathek kann keine Videos mehr abspielen

### ISSUE THREAD

**Issue by zamuehl** [prof-membrane/plugin.video.ardmediathek_de#31]
Betriebssystem: LibreElec 8.0.2

Kodi Version: 17.3 Git 147cec4

Add-on Version: 5.1.0 von sabres

Hallo zusammen,

seit 2 Tagen geht das ARD Add-on leider nicht mehr: Beim Öffnen eines Filmes kommt unten stehender Fehler. Getestet habe ich Tatorts, Babylon Berlin, Tagesschau.

Alle verfügbaren Updates sind installiert.

Ich hoffe, ich habe alle Daten niedergeschrieben, falls nicht, bitte nachfragen. 

DANKE für die Unterstützung.
Grüße

20:39:50.233 T:1484780448   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'finalUrl' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.ardmediathek_de/default.py", line 4, in <module>
                                                libard.list()
                                              File "/storage/.kodi/addons/script.module.libard/lib/libard.py", line 142, in list
                                                libMediathek.play(libArdPlay())
                                              File "/storage/.kodi/addons/script.module.libard/lib/libard.py", line 135, in libArdPlay
                                                return libardplayer.getVideoUrl(videoID = params['documentId'])
                                              File "/storage/.kodi/addons/script.module.libard/lib/libardplayer.py", line 24, in getVideoUrl
                                                return fetchJsonVideo(videoID)
                                              File "/storage/.kodi/addons/script.module.libard/lib/libardplayer.py", line 37, in fetchJsonVideo
                                                if finalUrl.startswith('//'):
                                            UnboundLocalError: local variable 'finalUrl' referenced before assignment
                                            -->End of Python script error report<--
20:39:50.271 T:1962050304   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.ardmediathek_de/?documentId=56949560&url=https%3A%2F%2Fappdata.ardmediathek.de%2Fappdata%2Fservlet%2Ftv%2Fplayer%2F56949560%3FbcastId%3D54319834%26json&mode=libArdPlay]
20:39:52.134 T:1391457184   ERROR: ExtractFrame: Could not decode a frame

**Comment by MRLB** [comment]
Gibt es dazu schon einen Hotfix?

**Comment by MRLB** [comment]
Oder ist es da eine zeitintensive Neuentwicklung notwendig?

**Comment by zamuehl** [comment]
Memrane, could you please help?
thx.

**Comment by 68000a** [comment]
Schau mal [hier](https://www.kodinerds.net/index.php/Thread/4055-Mein-Repo-f%C3%BCr-verschiedene-Videoaddons/?postID=489593#post489593)

Hatte das Problem ebenfalls mit "Babylon Berlin" und hab's kurzerhand selbst behoben.

**Comment by zamuehl** [comment]
> Schau mal hier
>Hatte das Problem ebenfalls mit "Babylon Berlin" und hab's kurzerhand selbst behoben.
@68000a Cool, super, vielen Dank!!! Es hat funktioniert.

**Comment by 68000a** [comment]
Es gibt ein Update, schaut mal [hier](https://www.kodinerds.net/index.php/Thread/4055-Mein-Repo-f%C3%BCr-verschiedene-Videoaddons/?postID=496740#post496740)
