### ISSUE TITLE
410 Errors in log, no playback

### ISSUE THREAD

**Issue by david-morris** [prof-membrane/plugin.video.ardmediathek_de#33]
When I try to open a video (all the videos I have tried except Tagesschau videos) it does not play, and the following error shows up in the log:

```
2020-07-10 14:52:04.644 T:140320708736768   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://www.ardmediathek.de/img/standard/00/48/20/91/94/-2114473875/16x9/384?mandant=ard
2020-07-10 14:52:05.111 T:140320708736768   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://www.ardmediathek.de/img/standard/00/46/87/29/86/-2114473875/16x9/384?mandant=ard
2020-07-10 14:52:08.600 T:140320691951360   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 410: Gone
                                            Traceback (most recent call last):
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.ardmediathek_de/default.py", line 4, in <module>
                                                libard.list()
                                              File "/var/lib/kodi/.kodi/addons/script.module.libard/lib/libard.py", line 149, in list
                                                l = modes.get(mode,libArdListMain)()
                                              File "/var/lib/kodi/.kodi/addons/script.module.libard/lib/libard.py", line 92, in libArdListVideosSinglePage
                                                items,nextPage = libardlisting.listRSS(params['url'],page)
                                              File "/var/lib/kodi/.kodi/addons/script.module.libard/lib/libardlisting.py", line 22, in listRSS
                                                response = libMediathek.getUrl(url)
                                              File "/var/lib/kodi/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 32, in getUrl
                                                return _request(url,headers,post)
                                              File "/var/lib/kodi/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 56, in _request
                                                response = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                                return self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 410: Gone
                                            -->End of Python script error report<--
2020-07-10 14:52:08.604 T:140320742307584   ERROR: GetDirectory - Error getting plugin://plugin.video.ardmediathek_de/?mode=libArdListVideosSinglePage&name=Most%20viewed&url=http%3a%2f%2fwww.ardmediathek.de%2ftv%2fMeistabgerufene-Videos%2fmehr%3fdocumentId%3d21282514%26m23644322%3dquelle.tv%26rss%3dtrue
2020-07-10 14:52:08.612 T:140321223305920   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ardmediathek_de/?mode=libArdListVideosSinglePage&name=Most%20viewed&url=http%3a%2f%2fwww.ardmediathek.de%2ftv%2fMeistabgerufene-Videos%2fmehr%3fdocumentId%3d21282514%26m23644322%3dquelle.tv%26rss%3dtrue) failed
```

I wouldn't be surprised if that isn't the reason the video won't play, since I get the following when I open a Tagesschau video:

```
2020-07-10 14:55:56.161 T:140320691951360   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://www.ardmediathek.de/img/standard/00/73/98/62/26/2121327408/16x9/1920?mandant=ard
2020-07-10 14:55:56.162 T:140320717129472   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://www.ardmediathek.de/img/standard/00/66/04/41/52/2121327408/16x9/1920?mandant=ard
2020-07-10 14:55:56.270 T:140320608089856   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://www.ardmediathek.de/img/standard/00/10/35/65/20/-1774185891/16x9/1920?mandant=ard
2020-07-10 14:55:56.634 T:140320742307584   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://www.ardmediathek.de/img/standard/00/60/83/42/50/-1774185891/16x9/1920?mandant=ard
2020-07-10 14:55:57.306 T:140320691951360   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://www.ardmediathek.de/img/standard/00/07/64/05/74/2121327408/16x9/1920?mandant=ard
2020-07-10 14:56:00.694 T:140320691951360   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://www.ardmediathek.de/img/standard/00/77/64/73/40/-1774185891/16x9/384?mandant=ard
2020-07-10 14:56:01.404 T:140321223305920  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.ardmediathek_de/?documentId=77647336&url=https%3A%2F%2Fappdata.ardmediathek.de%2Fappdata%2Fservlet%2Ftv%2Fplayer%2F77647336%3FbcastId%3D4326%26json&mode=libArdPlay
```

I am in Germany, and I don't have any proxy.

**Comment by Windsurfer87** [comment]
I have exactly the same problem. Fresh installed:

LibreELEC v 9.2.6

`````
2021-03-05 19:12:05.400 T:1807721344   DEBUG: CPythonInvoker(7, /storage/.kodi/addons/plugin.video.ardmediathek_de/default.py): start processing
2021-03-05 19:12:05.439 T:1807721344   DEBUG: -->Python Interpreter Initialized<--
2021-03-05 19:12:05.439 T:1807721344   DEBUG: CPythonInvoker(7, /storage/.kodi/addons/plugin.video.ardmediathek_de/default.py): the source file to load is "/storage/.kodi/addons/plugin.video.ardmediathek_de/default.py"
2021-03-05 19:12:05.439 T:1807721344   DEBUG: CPythonInvoker(7, /storage/.kodi/addons/plugin.video.ardmediathek_de/default.py): setting the Python path to /storage/.kodi/addons/plugin.video.ardmediathek_de:/storage/.kodi/addons/script.module.libard/lib:/storage/.kodi/addons/script.module.libmediathek3/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
2021-03-05 19:12:05.440 T:1807721344   DEBUG: CPythonInvoker(7, /storage/.kodi/addons/plugin.video.ardmediathek_de/default.py): entering source directory /storage/.kodi/addons/plugin.video.ardmediathek_de
2021-03-05 19:12:05.440 T:1807721344   DEBUG: CPythonInvoker(7, /storage/.kodi/addons/plugin.video.ardmediathek_de/default.py): instantiating addon using automatically obtained id of "plugin.video.ardmediathek_de" dependent on version 2.25.0 of the xbmc.python api
2021-03-05 19:12:05.621 T:1807721344   DEBUG: {'url': 'http://www.ardmediathek.de/tv/Meistabgerufene-Videos/mehr?documentId=21282514&m23644322=quelle.tv&rss=true', 'name': 'Meistgesehen', 'mode': 'libArdListVideosSinglePage'}
2021-03-05 19:12:05.622 T:1807721344   DEBUG: http://www.ardmediathek.de/tv/Meistabgerufene-Videos/mehr?documentId=21282514&m23644322=quelle.tv&rss=true&mcontents=page.1
2021-03-05 19:12:05.743 T:1807721344   DEBUG: Previous line repeats 1 times.
2021-03-05 19:12:05.743 T:1807721344   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 410: Gone
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.ardmediathek_de/default.py", line 4, in <module>
                                                libard.list()
                                              File "/storage/.kodi/addons/script.module.libard/lib/libard.py", line 149, in list
                                                l = modes.get(mode,libArdListMain)()
                                              File "/storage/.kodi/addons/script.module.libard/lib/libard.py", line 92, in libArdListVideosSinglePage
                                                items,nextPage = libardlisting.listRSS(params['url'],page)
                                              File "/storage/.kodi/addons/script.module.libard/lib/libardlisting.py", line 22, in listRSS
                                                response = libMediathek.getUrl(url)
                                              File "/storage/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 32, in getUrl
                                                return _request(url,headers,post)
                                              File "/storage/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 56, in _request
                                                response = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 410: Gone
                                            -->End of Python script error report<--
2021-03-05 19:12:05.743 T:1807721344   DEBUG: onExecutionDone(7, /storage/.kodi/addons/plugin.video.ardmediathek_de/default.py)
2021-03-05 19:12:05.744 T:1937009088   DEBUG: ------ Window Init (DialogNotification.xml) ------
2021-03-05 19:12:05.756 T:1807721344    INFO: Python interpreter stopped
2021-03-05 19:12:05.756 T:1807721344   DEBUG: Thread LanguageInvoker 1807721344 terminating
2021-03-05 19:12:05.762 T:1664889728   ERROR: GetDirectory - Error getting plugin://plugin.video.ardmediathek_de/?url=http%3A%2F%2Fwww.ardmediathek.de%2Ftv%2FMeistabgerufene-Videos%2Fmehr%3FdocumentId%3D21282514%26m23644322%3Dquelle.tv%26rss%3Dtrue&name=Meistgesehen&mode=libArdListVideosSinglePage

`````
